spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/task_management
    username: zhenishova
    password: 123456
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update

  server:
    port: 8080